# -*- coding: utf-8; -*-
#+STARTUP: hidestars
#+STARTUP: logdone
#+PROPERTY: Effort_ALL  0:10 0:20 0:30 1:00 2:00 4:00 6:00 8:00
#+COLUMNS: %38ITEM(Details) %TAGS(Context) %7TODO(To Do) %5Effort(Time){:} %6CLOCKSUM{Total}
#+PROPERTY: Effort_ALL 0 0:10 0:20 0:30 1:00 2:00 3:00 4:00 8:00
#+LaTeX_CLASS: article
#+LaTeX_HEADER: \usepackage{geometry}  
#+LaTeX_HEADER: \geometry{a4paper}   
#+LaTeX_HEADER: \usepackage{graphicx}
#+LaTeX_HEADER:\usepackage{amssymb}
#+LaTeX_HEADER:\usepackage{fontspec,lipsum}
#+LaTeX_HEADER:\defaultfontfeatures{Ligatures=TeX}
#+LaTeX_HEADER:\setromanfont{Minion Pro}
#+LaTeX_HEADER:\setsansfont{Myriad Pro}
#+OPTIONS: toc:nil num:nil
#+TITLE:     Notes on fast particle and beam plasma interaction
#+AUTHOR:    N. Vianello
#+EMAIL:     nicola.vianello@igi.cnr.it

* Letteratura
** Lista articoli da leggere
   [/] Ecco una lista di possibili articoli da Leggere 
   List 
   - [ ] Vlad et al. Nucl. Fusion (2009) vol. 49 pp. 07502
   - [X] Albergante et al. Phys. Plasmas (2009) vol. 16 (11) pp. 112301-8
   - [X] Shinohara et al. Nucl. Fusion (2001) vol. 41 pp. 603
   - [X] Briguglio et al. Phys. Plasmas (2007) vol. 14 (5) pp. 055904
   - [ ] Vlad et al. Riv Nuovo Cimento (1999) vol. 22 (7) pp. 1-97
   - [ ] Vlad et al. Nucl. Fusion (2006) vol. 46 (1) pp. 1-16
   - [ ] Vlad et al. AIP Conference Proceedings (2006)
   - [ ] Zonca et al. Plasma Phys. Control. Fusion (2006) vol. 48 (12B) pp. B15-B28
   - [ ] Pinches et al. Plasma Phys. Control. Fusion (2004) vol. 46 pp. B187-B200
   - [ ] Chen & Hasegawa, PoF vol 17 pag 1399 (1974)
   - [ ] Chen, PoP vol 1 pag 1519 (1994)
   - [X] Fasoli, Nucl. Fusion 47 S264 (2007)

* Appunti e considerazioni
** Vlad et al. Riv Nuovo Cimento (1999) vol. 22 (7) pp. 1-97
*** Teoria Lineare
**** Plasma infinito ed omogeneo
    Si parte dalle equazioni dell'MHD ideale con conservazione della massa, equazione del moto, equazione di stato, 
    legge di Ohm ideale e le equazioni di maxwell. 
    Nel caso di un plasma infinito omogeneo e linearizzando rispetto ad una perturbazione generica 
    $f(\mathbf{r},t)=\hat{f}e^{{-(i\omega t \mathbf{k}\cdot \mathbf{r})}}$ is ottiene il set di equazioni che descrivono le 
    onde in un plasma infinito ed omogeneo. In particolare si hanno due branch particolari.
    + *Shear Alfven Waves* che soddisfano alla relazione di
      dispersione \omega^2=\omega_A^2 = k_{\parallel}^2v_A^2. Che non
      dipendono dal vettore d'onda perpendicolar k_{\perp} e sono
      un'onda *puramente trasversa* con la perturbazione di campo
      magnetico parallela alla perturbazione di velocita e
      perpendicolare al campo magnetico di equilibrio. Dal momento che
      siamo in MHD ideale dall'equazione di Ohm otteniamo che la
      componente di velocita perpendicolare e' la velocita di drift
      E\times B. Conseguentemente il moto e' incomprimibile (\nabla v
      =0) e non si hanno perturbazioni di densita e pressione. L'onda
      di shear alfven deriva dal bilancio del termine inerziale
      $\rho dv/dt$ e dalla /magnetic field line tension/ $\mathbf{J}\times\mathbf{B}$
    + *Fast magneto-acoustic wave* con una frequenza \omega_f maggiore
      della frequenza di alfven. Se vale l'approssimazione di $\beta
      \ll 1$ allora la fast-magnetoacoustic-wave ha una relazione di
      dispersione del tipo \omega_f^2 =
      (k_\perp^2+k_\parallel^2)v_A^2. Si dimostra che nel limite di
      \beta<1 il rapporto fra la perturbazione di pressione cinetica e
      la perturbazione di pressione magnetica e' dell'ordine /O(\beta)/
    + *Slow magneto-acoustic wave* In questo caso si ha che la
      frequenza e' minore della frequenza di Alfven ed ancora nel caso
      $\beta \ll 1$ la relazione di dispersione e' del tipo \omega_s^2
      \approx k_\parallel^2 v_s^2. Il fluido e' dominato dal moto
      parallelo mentre la compressione del campo magnetico e'
      dell'ordine /O(\beta)/ rispetto a quella cinetica
    Quella piu' instabile e' quella di *shear alfven* sia perche'
    incomprimibile che perche' con una velocita di gruppo parallela al
    campo.

**** Non uniform slab configuration
    Consideriamo ora un equilibrio 1D con un campo magnetic sheared
    del tipo $\mathbf{B}_0(x)=B_{0y}(x)\mathbf{e}_y +
    B_{0z}(x)\mathbf{e}_z$. L'equazione di equilibrio diventa
    $d_{x}\left(P_0+\frac{B_0^2}{8\pi}\right)=0$. La trattazione
    continua in funzione di una generica funzione di *displacement*
    \delta\mathbf{v}=\partial_t \xi. In questo modo
    arriva ad una equazione d'onda che prevede le stesse tre branche
    ma che sono accoppiate fra loro. In particolare esiste una
    singolarita per $\epsilon = \omega\rho_m\mu_0-\k_{\parallel}^2B^2$
    in cui troviamo le due relazioni di dispersione rispettivamente
    dell'onda di shear alfven ed un'altra relazione. Questa
    singolarita' e' causa del fenomeno del *phase
    mixing*. Concettualmente la trattazione continua nell'ipotesi di
    un B_0=B_0e_z ed una densita dipendente dalla variabile x. In
    particolare si ipotizza di scrivere ciascuna perturbazione come
    una somma di perturbazioni locali ciascuna delle quali soddisfa
    l'equazione D_A \psi_{Al}(z|x) = 0 con D_A operatore di Alfven
    della forma \partial^2/\partial z^2 + \omega2/v_A^2. In
    particolare si ottiene una /local dispersion relation/ della forma
    $\omega^{2} = \omega_{Al} (x_{Rl})$ che e' soddisfatta alla
    posizione dove lo spettro continuo delle onde di shear alven
    risuona. Il concetto di accoppiamento fra le onde shear alfven e
    le onde compressionali implica che *le onde compressionali che
    hanno una velocita di gruppo trasversale al campo magnetico
    accumulano energia nella risonanza delle onde di shear alfven*. Un
    analisi al limite asintotico $\omega_{Al}t \longrightarrow \infty$
    rivela una divergenza nel vettore d'onda k_x che deriva dalla non
    validita' del limite MHD alle scale piccole. Tale non validita' e'
    dovuta alla dinamica delle piccole scale ad esmpio per la presenza
    di un campo elettrico parallelo finito ($\delta E_{\parallel}$) ad
    esempio indotto da effetti di raggio di larmor finito o da una
    piccola ma non trascurabile inerzia elettronica. Includendole si
    puo' tener conto di una propagazione finita di energia attraverso
    le superfici risonanti. Nell'ipotesi di $m_e/M_i \ll \beta_{e} \ll
    1$ otteniamo una equazione per le onde KAW. In particolare si
    arriva ad una equazione della forma

    \begin{equation}
    [4\omega^{2}\nabla_{\perp}^{2}\rho_{K}\nabla_{\perl}^{2}+\nabla_{\perp}\cdot\epsilon_{Al}\nabla_{\perp}]\hat{\xi_{xl}}=0
    \end{equation}
    dove $\rho_{K}$ tiene conto del *Landau damping* ionico ed
    elettronico. Si forma un *boundary layer* attorno alla risonanza
    dell'onda di shear Alfven. L'equazione descrive il *mode
    conversion* da un'onda MHD ad una instabilita a piccola scala. La
    relazione di dispersione si puo' anche scrivere nella forma $\omega^{2}=(1+4k_{\perp}^{2}\rho_{K})\omega_{Al}^{2}$.

**** Onde in un equilibrio assial simmetrico non uniforme generico.
    Consideriamo ora le equazioni che governano le onde di Shear Alfven
    in un equilibrio generale con un grado di simmetria rispetto alle
    rotazioni ipotizziamo rispetto all'asse z. Si concentra sul caso
    ad alto numero toroidale alto n con lunghezze caratteristice della
    forma $\lambda_{\per}=a/n$ $\lambda_{\parallel}=R_0$ ed $n \ll
    1$. L'equazione di base da cui si parte e' l'equazione di
    continuita' di carica per la perturbazione di corrente
    $\nabla\cdot \delta\mathbf{J} = 0$ che si distingue in parte
    perpendicolare e parte parallela. La componente di corrente
    parallela si scrive in funzione del potenziale vettore 

    \begin{equation}
    \delta J_{\parallel} = -\frac{c}{4\pi}\nabla_{\perp}^{2}\delta
    A_{\parallel} (1+O (\frac{a}{nR_{0}}))
    \end{equation}
    Inoltre il potenziale vettore puo' essere legato al potenziale
    scalare qualora si consideri la legge di Ohm parallela (ideal)
    $\delta E_{\parallel} = 0$. La componente perpendicolare di
    corrente viene invece calcolata a partire dall'equazione di
    bilancio delle forze in cui si tiene conto che il potenziale
    scalare si ricava sempre dalla legge di Ohm ($B_0\times\delta
    v_{\perp} = -c\nabla_{\perp}\delta\phi)$ e la perturbazione di
    pressione si ottiene come $\delta P \approx \left(
    \frac{ck_{\perp}}{\omega B_{0}}\frac{\partial P_{0}}{\partial
    r}\delta \phi\right)$ vale a dire perturbazione di pressione e di
    potenziale sono legate fra di loro. Si nota che dal momento che
    siamo con $n \ll 1$ e con una localizzazione radiale del modo, e
    che i modi sono caratterizzati da tempi dell'ordine dello shear
    Alfven time, piu' lungo rispetto al caso comprimibile. Questo
    implica che il plasma sia incomprimibile $4\pi \delta P =
    B_{0}\delta B_{\parallel}=0$. Si arriva ad una equazione per la
    vorticita totalmente generale

    \begin{equation}
    B_{0}\hat{\mathbf{b}}\cdot\nabla\left[\frac{1}{B_{0}}\nabla_{\perp}^{2}\hat{\mathbf{b}}\cdot\nabla\delta\phi\right] + 
    \nabla\cdot\left[\frac{4\pi\rho_{0}}{B_{0}^{2}}\omega^{2}\nabla_{\perp}\delta\phi\right]-
    8\pi\mathbf{k}\times\frac{\mathbf{B}_{0}}{B_{0}^{2}}\cdot\nabla_{\perp}\left[\left(\frac{\mathbf{B}_{0}\times\nabla
    P_{0}}{B_{0^{2}}}\right)\cdot\nabla_{\perp}\delta\phi\right]=0
    \end{equation}

**** Waves in a cylinder
** L. Chen, Phys. Plasmas 1, 1519 (1994) + ST Tsai and L Chen PoF B 5, 3284 (1993)
Quasi incomprensibile :-(.
Due cose importanti. Nel shear Alfven continuum esistono due gap:
1. Kinetic Balloning Modes (KBM) con 0\leq \omega \leq \omega_{*pic}
   where \omega_{*pic} is the core ion diamagnetic drift frequency
2. Toroidal Alfven Mode (TAM) con \omega_l^2\leq\omega\leq\omega_u^2
   where \omega_{l,u}^2 = (\omega_A^2/4)(1\mp\epsilon_0) and \epsilon_0=2(r/R_0+\Delta^{'})
Generally KBM gap is at lower frequency
** A. Fasoli, Nucl. Fusion 47
- Is it crucial to understand the behavior of fast ion and fast
  particle as these are expected to play a major role in achieving and
  controlling optimal burning plasma scenario with external heating
  and/or current drive
- BPI (Beam Plasma Interaction) studies resembles alpha particle
  behaviour in burning plasmas although contrary to fusion alphas
  stron anisotropy in the phase space distribution of injected or
  externaly induced fast ions are expected.
- One foundamental issue is the understanding of the interaction of
  alpha particles/energetic ions with plasma waves and instabilities
  possibly leading to their redistribution/losses.
- *\tau_{Beam Slowing Down}/\tau_E* determines the time scale for the
  response of the plasma temperature to the plasma self-heating
- Existing experiment/theoretical work with N-NBI performed in JT-60 Upgrade
  + Kusama PPCF 41 (1999). Ellipticity Induced AE modes excited at q=1
    surface via ICRF (derived by the coupling of two shear Alfven
    waves with poloidal mode number m and m+\Delta m con \Delta m = 2
    (sono Ellipticity induced)). These high frequency modes are stabilized via
    NNBI injection which enhance the damping of EAE. Indeed the net
    contribution of NNB injection is damping as the injection energy
    of the NNB is not high enough compared to v_A and the angular
    frequency of observed EAE modes is relatively large compared to
    the calculated diamagnetic drift frequency of NNB ions. Further
    stabilization is due to the addition of beam ion landau damping
  + Kusama NF 38 1837 (1999): Excitation and stabilization of AE modes
    via NNBI injection. In weak shear plasma TAE observed to be
    distabilized with <\beta_h> \approx 0.1\%. At higher $\beta$ of
    $\langle\beta_{h}\rangle 0.2$ \% a burst mode occurs in the range
    $\omega \leq \omega_{TAE}$ and the mode frequency changes rapidly
    by $\sim$ 20 kHz. The chirping modes appear in an arly phase of
    the NNB injection and the mode frequency starts to chirp from
    inside the Alfven continuum and increases to the TAE
    frequency. The chirping modes are excited only in a duration as
    long as the slowing down time of NNB ions after the start of NNB injection.
  + Kramer NF 40 1383 (2000):They create fast particles via ICRF
    heating and NNBI. Injection of an N-NBI into a sawtoothing plasma
    significantly increase the sawtooth period. The experiment has
    been performed to check the possibility of sawtooth oscillations
    through a population of passing energetic particles. The time
    period of sawtooth were increased of a factor 2.5 through a
    modification of the q profile. It has been recognized that fast
    particle population were deposited inside the q=1 surface. It is
    important to note that N-NBI fast particle experiment are
    foundamental as \alpha-particles are expected in ITER to be
    isotropic in distribution and N-NBI can provide information on
    passing particles, complementary to ICRF which is well suited for
    trapped particles
- Concerning sawtooth stabilization/destabilization stabilization
  through NBI obtaedin on DIII-D (Heidbrink NF 39) and JT-60 as
  reported above with N-NBI.
- It has been proposed that EPMs are leading cause of monster sawtooth crashes.
- *Progress in understanding some aspects of the MHD instability that
  leads to sawtooth has been sufficiently progreded to allow scenarios
  for controlling the sawtooth period to be designed theoretically and
  experimentally implemented*
- However as fast particles strongly stabilize sawteeth, long sawtooth
  periods are expected to lead to large crashes that can trigger NTMs
  also at relatively small beta.
- Large fast particle pressure in the plasma core can directly lead to
  *fishbones instabilities*. The fishbones are observed to trigger
  sawteeth, to eject different types of fast ions or are observed to
  trigger NTM.
- To be explored the effect of background turbulence on fast ions
- The presence of energetic ions in tokamak can results in various
  instabilities with frequency ranging from almost zero to harmonics
  of ion ion cyclotron frequency
- Typically instabilities in the Alfven frequency range are driven by
  fast-ion pressure gradient and may lead to the spatial
  redistribution or losses of fast ions whereas instabilites at higher
  current are generally driven by velocity space gradients.
- *AE instabilites are th most efficient in transporting energetic ions*
- To become unstable the drive from energetic ions has to exceed the
  global damping from background thermal plasma and the fast ions themeseves.
  \begin{equation*}
  \gamma =
  (\omega_{*}-\omega)F(v_{fast}/v_{Alfven})G(\Delta_{b}/\Delta_{m})
  \end{equation*}
  where $\omega_{*}$ is the fast-ion diamagnetic frequency. The function
  $F$ depends on the shape of fast-ion distribution and the function
  $G$ on the value of the orbit width parameter $\Delta_b \simeq
  q\rho_{fast}$ with respect to the radail scale of the mode with
  poloidal harmonic $m$. The function G assumes different values
  according to
  + $G=1$ if \Delta_b < (r/R)\Delta_m
  + $G = \mathcal{O}(m^{-1})$ if $r/R\Delta_m < \Delta_b <
    \Delta_m$. This is the regimes which gives the most unstable
    toroidal mode number and determines the maximum grow rate  for
    $k_{\perp}\rho_{fast}\approx 1$
  + $G=\mathcal{O}(m^{-2})$ if \Delta_b > \Delta_m
- First condition for AE to be unstable is $\omega < \omega_{*}$ which
  is general not realized for backgroun thermal ion in ITER relevant
  condition. Thus ion Landau damping is the main damping mechanism for
  low frequency AE in burning plasma with relatively high $\beta_i$. But
  for hihger frequency electron Landau damping becomes effective with 
  \begin{equation*}
  \gamma/\omega \sim (k_{\perp}\rho_{s})^{2} \exp(-[v_{A}/v_{e}]^{2})
  \end{equation*}
  The electron Landau damping becomes effective because of parallel
  electric field as large wave vector k_{\perp} account for a parallel
  electric field via Faraday's (k_{\perp}\times B \sim
  E_{\parallel}). Electron Landau damping contributes to the
  stabilization of AEs at high-n whereas in burning plasma condition
  even moderate n's (5-10) at the plasma edge are stabilized
- *Inconsistency between fluid and gyrokinetic codes in estimating
  continuum damping*
- From previous ITER Physics Database the main AE instabilities are
  observed to be due to plasma current and density profiles (GAEs) to
  the shape (TAE, EAE) and to kinetic effects (KAE, KTAE) but all
  these have been derived in conventionally positive shear scenario.
- Advanced Tokamak scenario with reversed shear operation reveals new
  type of instabilities as RSAEs (also known as Alfven Cascades). In
  this case two RSAE eigenmodes chirps in frequency with a chirping
  velocity proportional to the toroidal mode number $\partial_t f
  \propto n$ and merge into a TAE. The equation governing this merging
  is 
  \begin{align*}
  f_{RSAE}\simeq (n-m/q_{min})v_{A}/(2\pi R) \\
  f_{RSAE}\simeq ((m+1)/q-n)v_{A}/(2\pi R) \\
  f_{TAE} \simeq v_{A}/(4\pi q_{TAE}R) \qquad q_{TAE}=(m-1/2)/n
  \end{align*}
  RSAEs appears in advanced tokamak scenario driven by high-energy
  hydrogen minority ions and developes with a large spectrum of n numbers
- Stability of the mode determined by the balance between driving and
  damping mechanism which should be determined indipendently. This
  motivates dedicated active diagnostic system for the excitation and
  detection of MHD modes in the Alfven frequency range
- Collective effects are primarily due to modes pertaining to Alfven
  branch as these waves have group velocity in the parallel direction
  with velocities of the order of v_A and can thus resonantly
  interacts with MeV ions
- Excitation mechanism for these modes are provided by transit and
  precession-bounce resonances













** Schema generale nota
Beam-Plasma interaction and generally fast ion dynamics in burning
plasma condition should concentrate on different topics:
1. Interaction with low frequency MHD modes (kink, tearing, fishbones
   and sawteeth)
2. Kinetic balloning & localized interchange
3. High frequency AE modes in the linear phase
4. High frequency AE modes and EPM modes in the non-linear regimes
   which is generally accompained by fast particle convective
   transport and redistribution on fast time scales. Very important
   accessing the role of these instabilities in the fast particle
   redistribution is essential for using fast-particle-wave
   interaction as a tool for plasma control
5. Accessing the role of background turbulence in fast particle
   redistribution is one topics to be addresses

** Codici Utilizzati nei vari lavori
- [ ] Gyro-kinetic PENN (A.Fasoli NF 47)
- [ ] TASK/WM
- [ ] NOVA-K (global wave field)
- [ ] PENN (global wave field)
- [ ] CASTOR-K (global wave field, based on reduced kinetic mode)
- [ ] LIGKA Code (gyrokinetic)
