# -*- coding: utf-8; -*-
#+STARTUP: hidestars
#+STARTUP: logdone
#+PROPERTY: Effort_ALL  0:10 0:20 0:30 1:00 2:00 4:00 6:00 8:00
#+COLUMNS: %38ITEM(Details) %TAGS(Context) %7TODO(To Do) %5Effort(Time){:} %6CLOCKSUM{Total}
#+PROPERTY: Effort_ALL 0 0:10 0:20 0:30 1:00 2:00 3:00 4:00 8:00
#+LaTeX_CLASS:amsart
#+LaTeX_CLASS_OPTIONS:11pt
#+LATEX_HEADER:\usepackage{amssymb} 
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{geometry}
#+LATEX_HEADER:\geometry{a4paper}
#+LATEX_HEADER:\usepackage{colorx}  

* PAP/SPE-368473
** Questions
   The authors provide an interesting numerical work on non-linear
   simulation of ELMs using BOUT++ code. Apart from an initial
   benchmarking of the code against linear ideal MHD code in order to
   ensure the reliability of the reduced high-beta MHD approach used
   and of the numerical scheme, the authors concentrate on non-linear
   simulation.The problems arising from high-k structures are resolved
   including diamagnetic drifts and furthermore using hyper-resistive
   terms. The work is worth publishing basically in the present form,
   although I suggest the authors to address 
   the following points:

  1. Which would be the role of a non uniform resistivity profile in
     current evolution?
  2. Fig 4 (a). It is not clear the evolution of the inward displacement in the late non-linear regime (t > 60 \tau_a)
  3. Fig. 4 will results much more clear as a function of \psi rather than in SI
  4. In both fig 4 and 5 panel (c) different color lines would help the
     reader in following the evolution of the profiles
  5. How the profile evolution compare with experimental results coming
     for example from HRTS diagnostic or reflectometer? (although I
     understand the temporal resolution is lower than in the simulation)
  6. For the sake of clarity it would be useful to define \omega^{*}
  7. Fig (8b) suggests the presence of a certain degree of
     stochasticity: the authors, according to my opionion, should
     comment the issue, also considering their last comment on
     reconnection in the late stage of ELM eruption. 

* PPCF/383014/PAP. F.Sommer et al.
** The authors reports on various experimental evidences which help in characterizing MHD modes arising during Elmy H-mode named Edge Snakes.
The paper is well written and complete in describing the experimental
evidences although a few open issues exhisits on the theoretical
interpretation: but the authors correctly point out this part leaving
space for further investigation. The paper basically deserves
publications although before final acceptance the authors must add/clarify the following points
1. Paragraph 2.1. The authors refer to a spectrogram which might be
   included for a better understanding of the rich harmonic spectrum described
2. The authors might included a better explanation of the way they
   deduce the current as Biot-savart law might include a radial
   distance between the measurements and the current layer and
   furthermore it should be based on the total magnetic field (I
   presume they combine information coming from the balloning coils
   with information coming from the Mirnov coil)
3. It is not clear to me why a flattening of the density might occur
   inside the current layer or even better it should be discussed in
   term of particles sources (if magnetic islands exhist associated to
   edge snakes as ECE seems to suggest). Furthermore it should be
   better, if possible, if plot 3(b) and 3(c) should refer to the same time instants
   so that one could image what pressure perturbation should do
4. It could be interesting to know if the distribution of current in
   the Edge Snakes is co or counter current. Is there a way to
   determine it?

