#+STARTUP: hidestars
#+STARTUP: logdone
#+PROPERTY: Effort_ALL  0:10 0:20 0:30 1:00 2:00 4:00 6:00 8:00
#+COLUMNS: %38ITEM(Details) %TAGS(Context) %7TODO(To Do) %5Effort(Time){:} %6CLOCKSUM{Total}
#+PROPERTY: Effort_ALL 0 0:10 0:20 0:30 1:00 2:00 3:00 4:00 8:00
#+LaTeX_CLASS:amsart
#+LaTeX_CLASS_OPTIONS:11pt
#+LATEX_HEADER:\usepackage{amssymb} 
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{geometry}
#+LATEX_HEADER:\geometry{a4paper}
#+LATEX_HEADER:\usepackage{colorx}  

* PAP/SPE-368473
** Questions
   The authors provide an interesting numerical work on non-linear
   simulation of ELMs using BOUT++ code. Apart from an initial
   benchmarking of the code against linear ideal MHD code in order to
   ensure the reliability of the reduced high-beta MHD approach used
   and of the numerical scheme, the authors concentrate on non-linear
   simulation.The problems arising from high-k structures are resolved
   including diamagnetic drifts and furthermore using hyper-resistive
   terms. The work is worth publishing basically in the present form,
   although I suggest the authors to address 
   the following points:

  1. Which would be the role of a non uniform resistivity profile in
     current evolution?
  2. Fig 4 (a). It is not clear the evolution of the inward displacement in the late non-linear regime (t > 60 \tau_a)
  3. Fig. 4 will results much more clear as a function of \psi rather than in SI
  4. In both fig 4 and 5 panel (c) different color lines would help the
     reader in following the evolution of the profiles
  5. How the profile evolution compare with experimental results coming
     for example from HRTS diagnostic or reflectometer? (although I
     understand the temporal resolution is lower than in the simulation)
  6. For the sake of clarity it would be useful to define \omega^{*}
  7. Fig (8b) suggests the presence of a certain degree of
     stochasticity: the authors, according to my opionion, should
     comment the issue, also considering their last comment on
     reconnection in the late stage of ELM eruption. 

