# -*- coding: utf-8; -*-
#+STARTUP: hidestars
#+STARTUP: logdone
#+PROPERTY: Effort_ALL  0:10 0:20 0:30 1:00 2:00 4:00 6:00 8:00
#+COLUMNS: %38ITEM(Details) %TAGS(Context) %7TODO(To Do) %5Effort(Time){:} %6CLOCKSUM{Total}
#+PROPERTY: Effort_ALL 0 0:10 0:20 0:30 1:00 2:00 3:00 4:00 8:00
#+LaTeX_CLASS:amsart
#+LaTeX_CLASS_OPTIONS:11pt
#+LATEX_HEADER:\usepackage{amssymb} 
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{geometry}
#+LATEX_HEADER:\geometry{a4paper}
#+LATEX_HEADER:\usepackage{colorx}  

* PAP/SPE-368473
** Questions
   The authors provide an interesting numerical work on non-linear
   simulation of ELMs using BOUT++ code. Apart from an initial
   benchmarking of the code against linear ideal MHD code in order to
   ensure the reliability of the reduced high-beta MHD approach used
   and of the numerical scheme, the authors concentrate on non-linear
   simulation.The problems arising from high-k structures are resolved
   including diamagnetic drifts and furthermore using hyper-resistive
   terms. The work is worth publishing basically in the present form,
   although I suggest the authors to address 
   the following points:

  1. Which would be the role of a non uniform resistivity profile in
     current evolution?
  2. Fig 4 (a). It is not clear the evolution of the inward displacement in the late non-linear regime (t > 60 \tau_a)
  3. Fig. 4 will results much more clear as a function of \psi rather than in SI
  4. In both fig 4 and 5 panel (c) different color lines would help the
     reader in following the evolution of the profiles
  5. How the profile evolution compare with experimental results coming
     for example from HRTS diagnostic or reflectometer? (although I
     understand the temporal resolution is lower than in the simulation)
  6. For the sake of clarity it would be useful to define \omega^{*}
  7. Fig (8b) suggests the presence of a certain degree of
     stochasticity: the authors, according to my opionion, should
     comment the issue, also considering their last comment on
     reconnection in the late stage of ELM eruption. 

* PPCF/383014/PAP. F.Sommer et al.
** The authors reports on various experimental evidences which help in characterizing a relatively new 
MHD modes arising during Elmy H-mode named Edge Snakes.
The paper is well written and complete in describing the experimental
evidences although a few open issues exhisit on the theoretical
interpretation: but the authors correctly point out this part leaving
space for further investigation. The paper basically deserves
publications although before final acceptance the authors must add/clarify the following points
1. Paragraph 2.1. The authors refer to a spectrogram which might be
   included for a better understanding of the rich harmonic spectrum described
2. The authors might included a better explanation of the way they
   deduce the current from Biot-savart law indicating with more
   accuracy the radial distance from the probe location and the
   location of the current layer
3. The flattening of the density inside the magnetic islands which the
   authors claim to be associated to Edge Snakes should be discussed
   in term of particle sources, as edge particle sources coming from
   the first wall recycling could in principle lead to a density peaking.
   Furthermore it should be
   better, if possible, if plot 3(b) and 3(c) should refer to the same time instants
   so that one could image Edge Snakes in term of pressure perturbation
4. It could be interesting to know if the distribution of current in
   the Edge Snakes is co or counter current. Is there a way to
   determine it? Another point of interest could be if the current observed is
   located at the O or X point of the island but the authors already
   claims in the text that this require further measurements. Finally
   is this current layer (also considering its width) related
   to some reconnecting processes? I would suggest the authors to
   include some comments on the text or, if they repute this is beyond
   the scope of the article, if they could include some comments in
   the answer to the referee.

* PPCF/383344/PAP
The paper reports detailed analysis of edge properties comparing
discharges with type-II ELMs with discharges obtained in type-I ELMs or
in Nitrogen mitigated regimes. The article is basically well written
and interesting, in terms of experimental observation although not so
clear in terms of explanation or interpretation (but maybe this is
beyond the scope of the work). I think the article is worth of
publishing once the authors have clarified the following points
1) At page 6 in describing figure 3 the authors claim of transition
   from type-II to N-mitigated type I ELMS and adfirm that detailed
   analysis of magnetic pick-up coils have been carried out to
   distinguish from possible type-III ELMs. They adfirm the existence
   of 30 kHz oscillation without precursors. The existence of this 30
   kHz oscillation returns afterwords in the text but I think that a
   spectrogram of a magnetic pick-up coil could improve the
   understanding (although it appears later in the text) also because
   a very small variation in divertor current or power load can be
   inferred from figure 3.
2) In commenting fig. 6 (a) at page 8 the authors claims of an
   increase of the power spectrum during type-I ELM in the range 0-150
   kHz. Actually I think this figure is somehow misleading or prone to
   misunderstanding. I  do not understand if the 10 ms time
   window cited is composed joining different time slices including 1 single
   ELM event or if it is just a single time window including a single
   type-I ELM. In any case as type I exhibits a bursty behavior on
   magnetics (with duration less than 10 ms), a power spectrum
   will spread up in frequency causing the increase on all the
   range. I suggest the authors to cut this also as it does not
   include any further information in the comprehension. If other
   explanation can be done, far from what I've understood please clarify
3) Concerning figure 5 when type-I ELM appears? It is not so clear
   from the figure. Also I personally
   suggest to cut the part below 10 kHz (it's something different from
   what you want to highlight) as the color-code otherwise does not
   highlight sufficiently the component you are referring to
4) From Fig. 13 I can barely see the claimed increase of Ti in
   N-mitigated discharge in all the profile. Maybe a change of the
   y-scale for Ti measurement could help. I actually can't see any
   variation of the toroidal profile which can be inferred beyond the
   error bars. I suggest the authors to mitigate further any
   conclusion drawn from toroidal flow profile
5) In the conclusion, when the authors comment on fig. 9 the authors
   use the term structures but this is not the case as the figures are
   obtained with a time integration. So this is just the pattern of
   the fluctuations but can't be thought in terms of structures (nor
   in terms of propagation but this is clarified in the text)
6) Finally if possible I suggest he authors to include an error bars
   in the figure with the time evolution of the gradients of density
   temperature and pressure (at least an estimate)
* NF/414827/SPE
The article proposes analysis coming from a database of momentum
transport as collected by five different tokamaks, trying to establish
parametric dependence on adimensional parameter, highlightning
differences and similarities. The objective of this paper is
remarkable in this sense but in my opinion the paper proposes a list of
analysis without merging them in a comprehensive framework (although
this could be beyond the scope of the paper) but just as a
mere list. I think that, considering the importance of
this type of intermachine comparison, the paper should be published but
I suggest the authors to review it in order to merge all the analysis
in a more unitary overview. 
In particular I would like to point out the following points:
1) All the momentum studies have been done in the limit of
   Diffusive-Convective terms, and the authors correctly state on page
   4 that
   terms of the type of residual stress are neglected. I think it
   should be better to add a comment on the limit of this assumption
   and eventually what one would expect if considering a more complete
   form of the momentum flux
2) In the case of NSTX, if I understand correctly, you have included
   data where effects of Neoclassical toroidal viscosity should be
   evident. These data are not treated differently with respect to NBI
   blibs or other. Could you comment on this? Do you think there could
   be some differences in the two methods of perturbative momentum variation?
3) In commenting figure 3 I think the authors should mention that only
   NSTX exhibit a sufficient wide variation of Chi_i to observe a
   scaling, and that the claimed scaling can be derived only on a
   multi-machine comparison. I would like to point out the attention
   that the increase of \Chi_{\phi} with \Chi_i is exhibit an almost
   exponential behavior than a power law. Any comment on this?
4) In commenting figure 4 the authors claim differences in the ration
   \Chi_{\phi}/\Chi_i between the different machine with \Chi_{\phi}
   sometimes greater, sometimes smaller than \Chi_i. Any comment or
   possible interpretation is given on this fact. Could you provide
   some explanation?
5) I would suggest the authors to clarify why the observed decreasing
   of \Chi_{\phi}/\Chi_i with \rho_{pol}^{*} does not hold for low
   T_e/T_i in JT-60U. It is not clear to me.
6) Just a small point. In section 6 I would refer to Hamm's and
   Peeters's theory citing again the corresponding papers in line 5
   from the top. I makes the reading much more clear
7) Considering figure (14), if I interpet it correctly, as the two
   theories provide suitable interpolation for lower value of pinch
   velocity that the role played by the normalized density gradient is
   marginal. Could you comment on that? By the way, in particular in
   this case, I would appreciate that the data would appear with the
   corresponding error bars.
8) Again any comment is given to the inconsistency with the scaling
   with q_{95}.

Concluding I think that the subject of the paper and the data
available deserve the publication, but I think the authors should try
to make the paper somehow more fluent than the present form. I think
the suggestion given will help in this.
